# Generated by Django 5.1.3 on 2024-11-06 22:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID_Usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Usuario', models.CharField(max_length=100)),
                ('Clave', models.CharField(max_length=100)),
                ('ID_MT_Perfiles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Perfiles.mt_perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios_Sesion',
            fields=[
                ('ID_Usuarios_Sesion', models.AutoField(primary_key=True, serialize=False)),
                ('Inicio_Sesion', models.DateTimeField(default=django.utils.timezone.now)),
                ('Boton_1', models.IntegerField(default=0)),
                ('Boton_2', models.IntegerField(default=0)),
                ('Tiempo', models.IntegerField(null=True)),
                ('ID_Usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Users.usuarios')),
            ],
        ),
    ]
