# Generated by Django 5.1.3 on 2024-11-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_sesion',
            name='Tiempo',
            field=models.IntegerField(default=0),
        ),
    ]
