# Generated by Django 5.1.3 on 2024-11-06 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MT_Landing_Page',
            fields=[
                ('ID_MT_Landing_Page', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.BinaryField()),
                ('Titulo', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MT_Perfiles',
            fields=[
                ('ID_MT_Perfiles', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Perfil', models.CharField(max_length=100)),
                ('Jerarquia', models.IntegerField()),
                ('Descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID_Usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('ID_MT_Franquicias', models.IntegerField()),
                ('ID_MT_Sucursales', models.IntegerField()),
                ('Nombre_Usuario', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('Clave', models.CharField(max_length=100)),
                ('ID_MT_Perfiles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.mt_perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria_Usuarios_Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inicio_Sesion', models.DateTimeField()),
                ('Cierre_Sesion', models.DateTimeField()),
                ('Tiempo', models.IntegerField()),
                ('Boton_1', models.IntegerField()),
                ('Boton_2', models.IntegerField()),
                ('ID_Usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios_Sesion',
            fields=[
                ('ID_Usuarios_Sesion', models.AutoField(primary_key=True, serialize=False)),
                ('Inicio_Sesion', models.DateTimeField(default=django.utils.timezone.now)),
                ('Boton_1', models.IntegerField(default=0)),
                ('Boton_2', models.IntegerField(default=0)),
                ('Tiempo', models.IntegerField(null=True)),
                ('ID_Usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.usuarios')),
            ],
        ),
    ]
