# Generated by Django 5.1.3 on 2024-11-06 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='ID_MT_Perfiles',
        ),
        migrations.RemoveField(
            model_name='usuarios_sesion',
            name='ID_Usuarios',
        ),
        migrations.DeleteModel(
            name='Auditoria_Usuarios_Sesion',
        ),
        migrations.DeleteModel(
            name='MT_Perfiles',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Usuarios_Sesion',
        ),
    ]
