# Generated by Django 5.1.3 on 2024-11-06 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria_Usuarios_Sesion',
            fields=[
                ('ID_Auditoria_Usuarios_Sesion', models.AutoField(primary_key=True, serialize=False)),
                ('Inicio_Sesion', models.DateTimeField()),
                ('Cierre_Sesion', models.DateTimeField()),
                ('Tiempo', models.IntegerField()),
                ('Boton_1', models.IntegerField()),
                ('Boton_2', models.IntegerField()),
                ('ID_Usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Users.usuarios')),
            ],
        ),
    ]
