# Generated by Django 5.1.3 on 2024-11-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MT_Perfiles',
            fields=[
                ('ID_MT_Perfiles', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Perfil', models.CharField(max_length=100)),
                ('Jerarquia', models.IntegerField()),
                ('Descripcion', models.TextField()),
            ],
        ),
    ]
